export const synonyms = {
  abdominal_bloating: ["abdominal bloating", "belly bloating", "stomach bloating"],
  abdominal_cramps: ["abdominal cramps", "stomach cramps", "belly cramps"],
  abdominal_pain: ["abdominal pain", "stomach pain", "belly ache", "tummy pain"],
  anxiety: ["anxiety", "nervousness", "worry", "unease"],
  appetite_loss: ["loss of appetite", "no appetite", "not hungry"],
  arm_pain: ["arm pain", "arm ache"],
  back_pain: ["back pain", "lower back pain", "upper back pain", "backache"],
  blood_in_stool: ["blood in stool", "rectal bleeding", "blood in bowel movement"],
  blurred_vision: ["blurred vision", "vision problems", "vision disturbance", "difficulty seeing clearly"],
  body_ache: ["body ache", "body pain", "general ache"],
  bruising: ["bruising", "contusions", "black and blue marks"],
  burning_urination: ["burning urination", "painful urination", "dysuria"],
  chest_pain: ["chest pain", "chest discomfort", "tightness in chest", "pressure in chest", "stabbing chest pain", "pressure in chest"],
  chest_pain_exertion: ["chest pain on exertion", "angina", "exercise-induced chest pain"],
  chest_pain_sharp: ["sharp chest pain", "stabbing chest pain"],
  chest_pressure: ["chest pressure", "tight chest", "chest heaviness"],
  chest_tightness: ["chest tightness", "constricted chest"],
  chills: ["chills", "shivering", "cold shakes"],
  cold_sores: ["cold sores", "herpes", "blisters on lips"],
  confusion: ["confusion", "disoriented", "mental fog", "clouded thinking"],
  constipation: ["constipation", "difficulty passing stool", "hard stools"],
  cough: ["cough", "coughing"],
  cough_blood: ["coughing blood", "hemoptysis", "blood in cough"],
  cough_with_phlegm: ["productive cough", "cough with phlegm", "mucus cough"],
  depression: ["depression", "feeling down", "sadness", "low mood"],
  diarrhea: ["diarrhea", "loose stools", "runny stool", "frequent bowel movement"],
  difficulty_breathing: ["difficulty breathing", "dyspnea", "shortness of breath"],
  difficulty_concentrating: ["difficulty concentrating", "poor focus", "brain fog"],
  difficulty_swallowing: ["difficulty swallowing", "dysphagia", "trouble swallowing"],
  dizziness: ["dizziness", "lightheaded", "vertigo", "woozy"],
  dizziness_on_standing: ["dizziness on standing", "orthostatic dizziness", "lightheaded on standing"],
  dry_eyes: ["dry eyes", "xerophthalmia", "eye dryness"],
  dry_skin: ["dry skin", "xerosis", "rough skin"],
  ear_discharge: ["ear discharge", "fluid from ear", "ear drainage"],
  ear_fullness: ["ear fullness", "ear pressure", "ear blockage"],
  ear_pain: ["ear pain", "earache", "ear discomfort"],
  ear_popping: ["ear popping", "ear crackling", "ear clicking"],
  excessive_hunger: ["excessive hunger", "increased appetite", "polyphagia"],
  excessive_thirst: ["excessive thirst", "polydipsia", "dry mouth"],
  eye_pain: ["eye pain", "ocular pain", "eye ache"],
  eye_redness: ["eye redness", "red eyes", "conjunctival injection"],
  fainting: ["fainting", "passing out", "syncope"],
  fatigue: ["fatigue", "tired", "exhausted", "weary", "lethargic"],
  fever: ["fever", "high temperature", "temperature", "febrile"],
  fever_chills: ["fever and chills", "rigors", "shivering with fever"],
  frequent_urination: ["frequent urination", "peeing a lot", "urinate often"],
  frequent_urination_night: ["frequent urination at night", "nocturia"],
  hair_loss: ["hair loss", "balding", "thinning hair"],
  headache: ["headache", "head hurts", "head pain", "head ache"],
  headache_migraine: ["migraine", "severe headache", "throbbing head pain"],
  hearing_loss: ["hearing loss", "decreased hearing", "hard of hearing"],
  hoarseness: ["hoarseness", "voice changes", "raspy voice"],
  hoarseness_long_term: ["chronic hoarseness", "persistent hoarseness", "long-term voice changes"],
  insomnia: ["insomnia", "difficulty sleeping", "poor sleep"],
  irritability: ["irritability", "easily annoyed", "short temper"],
  joint_pain: ["joint pain", "arthralgia", "joint ache", "joint soreness"],
  joint_redness: ["joint redness", "inflamed joints", "red joints"],
  joint_stiffness: ["joint stiffness", "stiff joints", "difficulty moving joints"],
  joint_swelling: ["joint swelling", "inflamed joints", "puffy joints"],
  leg_cramps: ["leg cramps", "muscle cramps", "charley horse"],
  leg_pain: ["leg pain", "leg ache", "calf pain"],
  loss_of_consciousness: ["loss of consciousness", "passed out", "fainted", "blackout"],
  memory_loss: ["memory loss", "forgetfulness", "amnesia"],
  mouth_ulcers: ["mouth ulcers", "canker sores", "oral ulcers"],
  muscle_pain: ["muscle pain", "muscle ache", "myalgia", "muscle soreness"],
  nail_changes: ["nail changes", "brittle nails", "discolored nails"],
  nasal_congestion: ["nasal congestion", "stuffy nose", "blocked nose"],
  nausea: ["nausea", "queasy", "sick to stomach", "upset stomach", "throwing up"],
  nausea_after_eating: ["nausea after eating", "upset stomach after meals"],
  nausea_without_vomiting: ["nausea", "queasy"],
  neck_pain: ["neck pain", "neck ache", "stiff neck"],
  night_sweats: ["night sweats", "excessive sweating at night"],
  nosebleed: ["nosebleed", "epistaxis", "bleeding from nose"],
  numbness: ["numbness", "loss of sensation", "tingling", "pins and needles"],
  paleness: ["paleness", "pale skin", "pallor"],
  palpitations: ["heart palpitations", "irregular heartbeat", "fluttering in chest"],
  rash: ["rash", "skin rash", "red spots"],
  runny_nose: ["runny nose", "nasal drip", "rhinorrhea"],
  sensitivity_to_light: ["sensitivity to light", "photophobia", "light sensitivity"],
  skin_discoloration: ["skin discoloration", "skin color changes", "pigmentation changes"],
  skin_flaking: ["skin flaking", "peeling skin", "dry skin peeling"],
  skin_itching: ["skin itching", "itchy skin", "pruritus"],
  smell_loss: ["loss of smell", "anosmia", "can't smell"],
  sneezing: ["sneezing", "sneeze"],
  sore_throat: ["sore throat", "throat pain", "scratchy throat", "throat irritation"],
  sweating: ["excessive sweating", "sweaty", "profuse sweating", "diaphoresis"],
  swollen_feet: ["swollen feet", "foot edema", "puffy feet"],
  swollen_hands: ["swollen hands", "hand edema", "puffy hands"],
  swollen_lymph_nodes: ["swollen lymph nodes", "swollen glands", "lymphadenopathy"],
  swollen_tonsils: ["swollen tonsils", "enlarged tonsils", "tonsillitis"],
  taste_loss: ["loss of taste", "ageusia", "can't taste"],
  tearing_eyes: ["tearing eyes", "watery eyes", "epiphora"],
  thirst: ["thirst", "dry mouth", "dehydration"],
  throat_clearing: ["frequent throat clearing", "throat irritation", "constant throat clearing"],
  tingling: ["tingling", "pins and needles", "paresthesia"],
  tongue_pain: ["tongue pain", "burning tongue", "tongue soreness"],
  vomiting: ["vomiting", "throwing up", "puke", "barf"],
  vomiting_blood: ["vomiting blood", "hematemesis", "throwing up blood"],
  vomiting_persistent: ["persistent vomiting", "continuous vomiting", "repeated throwing up"],
  weakness: ["weakness", "lack of strength", "fatigue"],
  weight_gain: ["weight gain", "gaining weight", "unexplained weight gain"],
  weight_gain_unintended: ["unintended weight gain", "unexpected weight gain"],
  weight_loss: ["weight loss", "losing weight", "unintended weight loss"],
  weight_loss_unintended: ["unintended weight loss", "unexpected weight loss", "losing weight without trying"],
  wheezing: ["wheezing", "whistling sound when breathing"]
};